# Generated by Django 4.0.2 on 2022-03-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=25)),
                ('pass1', models.CharField(max_length=25)),
                ('pass2', models.CharField(max_length=25)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
